version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
        - db

  db:
    image:
      postgres:alpine
    restart:
      always
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=/api/v1
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./docker/frontend/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - DEV_CLIENT_IP=${DEV_CLIENT_IP}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro